version: '3'

services:
  coding-agent:
    build: .
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
